# Generated by Django 5.2.4 on 2025-07-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('total_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pertenece_a', models.CharField(max_length=200)),
                ('recibido_por', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
